import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JList;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Miguerubsk
 */
public class formulario extends javax.swing.JFrame {
    
    
    public static void leerfichero(ArrayList lista, String fichero) throws FileNotFoundException, IOException{
        FileReader f = new FileReader(fichero);
        BufferedReader b = new BufferedReader(f);
        String cadena;
        while((cadena = b.readLine())!=null) {
            lista.add(cadena);
    }
    };


    /**
     * Creates new form formulario
     */
    public formulario(ArrayList<String> listaidiomas) throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        languageSelector.setModel(new DefaultComboBoxModel(listaidiomas.toArray()));
        String rutaTextos = languageSelector.getSelectedItem()+".txt";
        String rutaLista = "lista"+languageSelector.getSelectedItem()+".txt";
        
        ArrayList<String> textos = new ArrayList<>();
        ArrayList<String> list = new ArrayList<>();
        try {
            leerfichero(textos, rutaTextos);
            leerfichero(list, rutaLista);
        } catch (IOException ex) {
            Logger.getLogger(formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Exit.setText(textos.get(0));
        Language.setText(textos.get(1));
        Exit.setText(textos.get(2));
        agregar.setText(textos.get(3));
        quitar.setText(textos.get(4));
        coso.removeAllItems();
        coso.setModel(new DefaultComboBoxModel(list.toArray()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExitAdvert = new javax.swing.JDialog();
        ExitAdvertText = new javax.swing.JLabel();
        ExitAdvertCancel = new javax.swing.JButton();
        ExitAdvertAccept = new javax.swing.JButton();
        languageSelector = new javax.swing.JComboBox<>();
        Exit = new javax.swing.JButton();
        Language = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        coso = new javax.swing.JComboBox<>();
        quitar = new javax.swing.JButton();
        Texto = new javax.swing.JTextField();

        ExitAdvert.setModal(true);
        ExitAdvert.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        ExitAdvertText.setText("jLabel2");

        ExitAdvertCancel.setText("jButton1");
        ExitAdvertCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitAdvertCancelActionPerformed(evt);
            }
        });

        ExitAdvertAccept.setText("jButton2");
        ExitAdvertAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitAdvertAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExitAdvertLayout = new javax.swing.GroupLayout(ExitAdvert.getContentPane());
        ExitAdvert.getContentPane().setLayout(ExitAdvertLayout);
        ExitAdvertLayout.setHorizontalGroup(
            ExitAdvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitAdvertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ExitAdvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExitAdvertLayout.createSequentialGroup()
                        .addComponent(ExitAdvertText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitAdvertLayout.createSequentialGroup()
                        .addComponent(ExitAdvertCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitAdvertAccept)
                        .addGap(109, 109, 109))))
        );
        ExitAdvertLayout.setVerticalGroup(
            ExitAdvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitAdvertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitAdvertText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ExitAdvertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitAdvertAccept)
                    .addComponent(ExitAdvertCancel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        languageSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        languageSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageSelectorActionPerformed(evt);
            }
        });

        Exit.setText("jButton1");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Language.setText("jLabel1");

        agregar.setText("jButton1");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        coso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        quitar.setText("jButton1");
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(887, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Exit)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Language)
                        .addGap(18, 18, 18)
                        .addComponent(languageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, Short.MAX_VALUE)
                .addComponent(coso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Language))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregar)
                            .addComponent(quitar)
                            .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(coso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 600, Short.MAX_VALUE)
                .addComponent(Exit)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void languageSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageSelectorActionPerformed
        
        String rutaTextos = languageSelector.getSelectedItem()+".txt";
        String rutaLista = "lista"+languageSelector.getSelectedItem()+".txt";
        
        ArrayList<String> textos = new ArrayList<>();
        ArrayList<String> list = new ArrayList<>();
        try {
            leerfichero(textos, rutaTextos);
            leerfichero(list, rutaLista);
        } catch (IOException ex) {
            Logger.getLogger(formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        coso.setModel(new DefaultComboBoxModel(list.toArray()));
        Exit.setText(textos.get(0));
        Language.setText(textos.get(1));
        Exit.setText(textos.get(2));
        agregar.setText(textos.get(3));
        quitar.setText(textos.get(4));
        
        
         
        
        
    }//GEN-LAST:event_languageSelectorActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        ExitAdvert.setVisible(true);
        ExitAdvert.setModal(true);
        ExitAdvert.setResizable(false);
        String rutaTextos = languageSelector.getSelectedItem()+".txt";
        
        ArrayList<String> textos = new ArrayList<>();
        try {
            leerfichero(textos, rutaTextos);
        } catch (IOException ex) {
            Logger.getLogger(formulario.class.getName()).log(Level.SEVERE, null, ex);
        }
        ExitAdvert.setTitle(textos.get(7));
        ExitAdvertCancel.setText(textos.get(6));
        ExitAdvertAccept.setText(textos.get(5));
        ExitAdvertText.setText(textos.get(8));
        ExitAdvert.setSize(256, 206);
        ExitAdvert.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_ExitActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String elemento = Texto.getText();
        Texto.setText(null);
    }//GEN-LAST:event_agregarActionPerformed

    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        coso.removeAllItems();
    }//GEN-LAST:event_quitarActionPerformed

    private void ExitAdvertAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitAdvertAcceptActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitAdvertAcceptActionPerformed

    private void ExitAdvertCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitAdvertCancelActionPerformed
        ExitAdvert.setVisible(false);
    }//GEN-LAST:event_ExitAdvertCancelActionPerformed

    private void TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        ArrayList<String> listaidiomas = new ArrayList<>();
        leerfichero(listaidiomas, "idiomas.txt");
        
        
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new formulario(listaidiomas).setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(formulario.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JDialog ExitAdvert;
    private javax.swing.JButton ExitAdvertAccept;
    private javax.swing.JButton ExitAdvertCancel;
    private javax.swing.JLabel ExitAdvertText;
    private javax.swing.JLabel Language;
    private javax.swing.JTextField Texto;
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox<String> coso;
    private javax.swing.JComboBox<String> languageSelector;
    private javax.swing.JButton quitar;
    // End of variables declaration//GEN-END:variables
}
